### ISSUE TITLE
Thumbnails for recent searchs

### ISSUE THREAD

**Issue by adeora7** [adeora7/hacktoberfest_progress#19]
Thumbnails can be saved for at least 5 recently searched users for quick search. One option for design can be round images/handles right above the search box.

**Comment by lmcjt37** [comment]
I could look into this and add the ability to store the data alongside it?

update: A thought on storing PR item data, is that the data could be out of date so would make sense to only store the username and thumbnails. What do you think?

**Comment by adeora7** [comment]
Yes, even I thought about it. Lets save user handle only in the thumbnail. @lmcjt37  And sure, please handle this also if you want to :)
