### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by lmcjt37** [adeora7/hacktoberfest_progress#26]
Fix typos, add missing explanations, improve formatting, etc.

**Comment by ehnydeel** [comment]
saw a typo in the README.md - would like to correct it. can u assign me?

**Comment by GitHug** [comment]
I am a bit too late to the party, and sorry for the duplicate, but I also fixed some spelling misstakes.

**Comment by nsmehta** [comment]
Hi, I am working on the typos in README.MD file

**Comment by sambhav2612** [comment]
I'm working on typos. also, I'm looking into vocabulary enhancements.

**Comment by khemmapon** [comment]
I'm working on improve formatting for popup.js file

**Comment by joseph-allen** [comment]
unending ticket, can be closed
