### ISSUE TITLE
Formatting for Contributors in Readme file

### ISSUE THREAD

**Issue by adeora7** [adeora7/hacktoberfest_progress#34]
Find better format to represent contributors in the readme file. It can be a table or thumbnails etc.

**Comment by subinoy7** [comment]
I am taking this

**Comment by adeora7** [comment]
@subinoy7 okay !

**Comment by subinoy7** [comment]
@adeora7 I have done some changes, please check it

**Comment by subinoy7** [comment]
@adeora7 If it is done please close it.

**Comment by adeora7** [comment]
@subinoy7 sure  !!
