### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by adeora7** [adeora7/hacktoberfest_progress#35]
Add contributors to readme file which are there in the contributors section of this repository.

**Comment by kincade71** [comment]
On it!

**Comment by double-slit** [comment]
@adeora7 I would like to work on this issue.

**Comment by susw12** [comment]
I have done a pull request for this.

**Comment by adeora7** [comment]
@rajatbajaj000 sorry someone else already commented.
@susw12 sorry, you have to comment first. If others don't work on it only then we can merge it.

**Comment by susw12** [comment]
Ok, no problem

**Comment by SampratiSimran** [comment]
Sure.

**Comment by lmcjt37** [comment]
@AleksandarStojanovikj don't forget to add your contributor profile (extra credit towards Hacktoberfest ;) )

**Comment by joseph-allen** [comment]
issue can be closed

**Comment by lmcjt37** [comment]
@joseph-allen have you added your contributor profile? 😉
