### ISSUE TITLE
403 error from GitHub

### ISSUE THREAD

**Issue by lmcjt37** [adeora7/hacktoberfest_progress#45]
If 403 error returned when calling API, we should probably handle this better.

Suggestion: Don't change any UI unless a ~200 is returned successfully.

**Comment by NicolasNSSM** [comment]
Can you add the steps to reproduce? I can only get a 422 when i input a non-existent username giving a never ending "Loading..."

**Comment by samyok** [comment]
I fixed it and submitted a PR. 
#47 -- Fix Issue #45

**Comment by joseph-allen** [comment]
issue from last year, can be closed @adeora7
