### ISSUE TITLE
Remove "pull requests" if no PRs

### ISSUE THREAD

**Issue by adeora7** [adeora7/hacktoberfest_progress#5]
Remove the "pull requests" section from the result box if there are no PRs.

**Comment by lmcjt37** [comment]
I can take this, put a PR after lunch

If you can give me permission :)

**Comment by adeora7** [comment]
@lmcjt37  sure !!

**Comment by modihere** [comment]
Can i submit a PR for this?

**Comment by adeora7** [comment]
@modihere sorry but @lmcjt37  already commented and he submitted the PR within a hour.

**Comment by modihere** [comment]
okay!
