### ISSUE TITLE
Pull Request details as a popup

### ISSUE THREAD

**Issue by adeora7** [adeora7/hacktoberfest_progress#6]
If the details of the Pull Requests in the results div can be showed as a popup only if someone clicks on a show details button, it will be better as now the length of the extension popup increases too much while displaying result.

**Comment by nycosborne** [comment]
Greeting, I found your project and have and few ideas. Can I contribute?

**Comment by adeora7** [comment]
Sure !! Feel free to add issues or create PRs. Just comment on the issue before starting to work so that there is no repetitive work. @nycosborne

**Comment by lmcjt37** [comment]
@nycosborne are you planning on publishing a PR for this issue? I can create one if not
