### ISSUE TITLE
Improve the UI

### ISSUE THREAD

**Issue by lmcjt37** [adeora7/hacktoberfest_progress#74]
Improve the UI in some way?

Make the results more prominent, improve the 'show results' overlay, better font?

**Comment by nelavensubas** [comment]
Hello,

May I handle this issue?

Nelaven

**Comment by meyfleur** [comment]
If this is still available i would love to improve the UI :)

**Comment by lmcjt37** [comment]
@meyfleur feel free to add any UI improvements - I have just merged a PR by @nelavensubas which adds a font style
