### ISSUE TITLE
Restrict Number of PRs to be displayed

### ISSUE THREAD

**Issue by adeora7** [adeora7/hacktoberfest_progress#8]
Restrict Number of PRs to be displayed in the results section. Currently all the PRs are displayed however maximum 4 PRs should be displayed.

**Comment by raindogg** [comment]
Hi, 

Submitted a [PR](https://github.com/adeora7/hacktoberfest_progress/pull/16) with this feature. Thanks for putting this out there!

**Comment by adeora7** [comment]
@raindogg  really nice and clean way to do it !!
